name: fitness_app
description: "FitFi - AI Powered Smart Fitness Coach"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.0
  shared_preferences: ^2.5.4
  sensors_plus: ^7.0.0
  flutter_local_notifications: ^21.0.0
  camera: ^0.12.0+1
  google_mlkit_pose_detection: ^0.14.1
  table_calendar: ^3.1.2
  timezone: ^0.11.0
  lottie: ^3.3.2
  archive: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/gym/
    - assets/sections/challange/
    - assets/sections/ufc/
    - assets/sections/gym focus area cards/
    - assets/sections/extra course card images/
    - assets/all_exercises/
